version: '3'

services:
  postgres:
    container_name: kc_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: kc_user
      POSTGRES_PASSWORD: cheiKoo7
      POSTGRES_DB: keycloak_db
    ports:
      - 5432:5432

  kc_one:
    container_name: kc1
    image: quay.io/keycloak/keycloak:20.0.5
    command: start
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres/keycloak_db?user=kc_user&password=cheiKoo7"
      # KEYCLOAK_FRONTEND_URL: "http://localhost:8080/auth/"
      # KC_HOSTNAME_URL: "http://localhost:8080"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KC_CACHE_STACK: UDP
      # KC_HTTP_ENABLED: true
      KC_PROXY: edge
      # KC_HOSTNAME: localhost
      # KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      # KC_HOSTNAME_STRICT_HTTPS: false
      # KC_HTTP_PORT: 8080
    depends_on:
      - postgres

  kc_two:
    container_name: kc2
    image: quay.io/keycloak/keycloak:20.0.5
    command: start
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres/keycloak_db?user=kc_user&password=cheiKoo7"
      # KEYCLOAK_FRONTEND_URL: "http://localhost:8080/auth/"
      # KC_HOSTNAME_URL: "http://localhost:8080"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KC_CACHE_STACK: UDP
      # KC_HTTP_ENABLED: true
      KC_PROXY: edge
      # KC_HOSTNAME: localhost
      # KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      # KC_HOSTNAME_STRICT_HTTPS: false
      # KC_HTTP_PORT: 8080
    depends_on:
      - postgres

  lb:
    container_name: kc_lb
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    depends_on:
      - kc_one
      - kc_two
